import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import Header from '@/ui/components/Header'
import React, { useEffect, useState } from 'react'

import dynamic from 'next/dynamic'
import Video from '@/ui/components/Video'

const ReactPlayer = dynamic(() => import("react-player"), {ssr: false});

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [urlVideo, setUrlVideo] = useState<string>();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <section>
        <div className='w-[200vw] absolute left-[-50%] top-50'>
          <Video />
        </div>
      </section>
    </>
  )
}
